config/routes.rb
PmsProject::Application.routes.draw do

  resources :users
	resources :projects do
		collection do
			get "search",:as=>"search_project"
		end
		resources :tasks do
			collection do 
				get "search",:as=>"search_task"
			end
		end
	end

  

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name
  has_many :tasks
  has_many :users
  
  scope :sorted, order('projects.id ASC')
  scope :by_name, lambda{|name| where(["name like (?)","%#{name}%"])}
  
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :project_id, :name
  
  belongs_to :project
  
  scope :sorted, order('tasks.id ASC')
  scope :by_name, lambda{|name| where(["name like (?)","%#{name}%"])}
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :password
  
  has_many :projects
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  layout 'style'
  
  def index
    @projects = Project.sorted
		
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show  
    @project = Project.find(params[:id])    
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
  	@users = User.all
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    if @project.save
      redirect_to(projects_path) 
      flash[:notice] = 'Project was successfully created.'
    else
      render('new')
    end

  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])
    
    if @project.update_attributes(params[:project])
      redirect_to(projects_path)
      flash[:notice] = 'Project was successfully updated.'
    else
      render('edit')
    end
    
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
  
  def search
  	@projects = Project.by_name(params[:name])
  	respond_to do |format|
      format.html 
      format.json { render json: @project }
    end
  end
  
  def result
  	@project = Project.find_by_name(params[:project]["name"])
  	redirect_to(show_project_path(@project))
  end
  
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  
  layout 'style'
  
  before_filter :find_project
  
  def index
    
    @tasks = @project.tasks
		
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
 
    @task = @project.tasks.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new(:project_id => params[:id])
		@projects = Project.sorted
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end
  
   # POST /tasks
  # POST /tasks.json
  def create
 
    @task = @project.tasks.new(params[:task])

      if @task.save
        redirect_to(project_tasks_path(@project))
        flash[:notice] = 'Task was successfully created.' 
      else
      	
        render('new')
      end
  end

  # GET /tasks/1/edit
  def edit
  	
    @task = @project.tasks.find(params[:id])

  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
  	@task = @project.tasks.find(params[:id])
    if @task.update_attributes(params[:task])
      redirect_to(project_tasks_path(@project))
      flash[:notice] = 'Task was successfully updated.'
    else
      render('edit')
    end
  end 
  
  
  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = @project.tasks.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to(project_tasks_path(@project)) }
      format.json { head :no_content }
    end
  end
  
  def search
  	@tasks = @project.tasks.by_name(params[:name])
  	respond_to do |format|
      format.html 
      format.json { render json: @project }
    end
  end
  
  def result
  	@project = Project.find_by_id(params[:id])
  	@task = Task.find_by_name(params[:task]["name"])
  	redirect_to(show_task_path(@task, @project))
  end
  
  
  private
  
  def find_project
    @project = Project.find(params[:project_id])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PmsProject</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/style.html.erb
<html>
	<head>
		 <link href="/stylesheets/style.css" rel="stylesheet" type="text/css" media="all"/>  
		 <%= javascript_include_tag "application" %>
  	 <%= csrf_meta_tags %>
	</head>
	<body>
		<div id="header">
      <h1>Project Management System</h1>
    </div>
    <div id="main">
     	<% if !flash[:notice].blank? %>
      <div class="notice">
        <%= flash[:notice] %>
      </div>
      <% end %>
      <div id="content">
        <%= yield %>
      </div>
    </div>
    <div id="footer">
      <p></p>
    </div>
	</body>
</html>

app/views/projects/_form.html.erb
<%= render(:partial => 'shared/error_messages', :locals => {:object => @project})%>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

app/views/projects/edit.html.erb
<%= link_to 'Show', project_path(@project) %>
<%= link_to 'Back', projects_path %>

<div class="subject edit">
  <h2>Edit Project : '<%= @project.name%>'</h2>

  <%= form_for(@project, :url=>project_path(@project)) do |f| %>
  
    <%= render(:partial => "form", :locals => {:f => f}) %>
    
    <div class="form-buttons">
      <%= f.submit("Update Project") %>
    </div>
    
  <% end %>
</div>

app/views/projects/index.html.erb
<%= link_to 'New Project', new_project_path, :class => 'action new'%><br/>

<%= link_to 'Search Project', search_project_projects_path %>

<h1>Listing projects</h1>

<table class="listing" border = 1>
  <tr>
    <th>Name</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th>Tasks</th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.created_at %></td>
    <td><%= project.updated_at %></td>
    <td><%= project.tasks.count %></td>
    <td><%= link_to 'Show', project_path(project) %>
    <%= link_to 'Edit', edit_project_path(project) %>
    <%= link_to 'Destroy', project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %>
    <%= link_to 'Tasks Details', project_tasks_path(project) %></td>
  </tr>
<% end %>
</table>

<br />

app/views/projects/new.html.erb
<%= link_to 'Back', projects_path %>

<div class="subject new">
  <h2>Create Project</h2>

  <%= form_for([@project]) do |f| %>
  
    <%= render(:partial => "form", :locals => {:f => f}) %>
    
    <div class="form-buttons">
      <%= f.submit("Create Project") %>
    </div>
    
  <% end %>
</div>

app/views/projects/search.html.erb
<%= link_to 'Back', projects_path %>

<div class="project search">
  <h2>Search Project</h2>

  <%= form_tag(search_project_projects_path,:method=>:get) do  %>
  
    <div class="field">

  	  <%= text_field_tag :name %>
  	</div>
    <div class="form-buttons">
      <%= submit_tag("Search Project") %>
    </div>
    
  <% end %>
  
</div>
<table class="listing" border = 1>
  <tr>
    <th>Name</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th>Tasks</th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.created_at %></td>
    <td><%= project.updated_at %></td>
    <td><%= project.tasks.count %></td>
    <td><%= link_to 'Show', project_path(project) %>
    <%= link_to 'Edit', edit_project_path(project) %>
    <%= link_to 'Destroy', project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %>
    <%= link_to 'Tasks Details', project_tasks_path(project) %></td>
  </tr>
<% end %>
</table>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Created at:</b>
  <%= @project.created_at %>
</p>

<p>
  <b>Updated at:</b>
  <%= @project.updated_at %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %>
<%= link_to 'Back', projects_path %>

app/views/shared/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
  <div id="errorExplanation">
    <h2><%= pluralize(object.errors.size, "error") %> prohibited this record from being saved</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<%= render(:partial => 'shared/error_messages', :locals => {:object => @task})%>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
    <%#= text_field_tag :name %>
  </div>

app/views/tasks/edit.html.erb
<%= link_to 'Show', project_task_path(@task,@project) %>
<%= link_to 'Back', project_tasks_path(@project) %>

<div class="task edit">
  <h2>Update Task</h2>

  <%= form_for(:task, :url => project_tasks_path( @project,@task)) do |f| %>
  
    <%= render(:partial => 'form', :locals => {:f => f}) %>
    
    <div class="form-buttons">
      <%= submit_tag("Update Task") %>
    </div>
    
  <% end %>
</div>

app/views/tasks/index.html.erb
<%= link_to("<< Back to Projects List", projects_path, :class => 'back-link') %><br/>
<%= link_to 'New Task', new_project_task_path(@project), :class => 'action new' %><br/>
<%= link_to 'Search Task', search_task_project_tasks_path(@project, @task) %>

<h1>Listing tasks</h1>

<table border = 1>
  <tr>
    <th>Name</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.created_at %></td>
    <td><%= task.updated_at %></td>
    <td><%= link_to 'Show',project_task_path(@project,task) %>
    <%= link_to 'Edit', edit_project_task_path( @project,task) %>
    <%= link_to 'Destroy', project_task_path(@project,task), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br/>

app/views/tasks/new.html.erb
<%= link_to 'Back', project_tasks_path(@project) %>

<div class="task new">
  <h2>Create Task</h2>

  <%= form_for([@project,@task]) do |f| %>
  
    <%= render(:partial => 'form', :locals => {:f => f}) %>
    
    <div class="form-buttons">
      <%= f.submit("Create Task") %>
    </div>
    
  <% end %>
</div>

app/views/tasks/search.html.erb
<%= link_to 'Back', project_tasks_path(@project) %>

<div class="task search">
  <h2>Search Task</h2>

  <%= form_tag(search_task_project_tasks_path(@project), :method => :get) do %>
  
    <div class="field">
  	  <%= text_field_tag :name %>
  	</div>
    <div class="form-buttons">
      <%= submit_tag("Search Task") %>
    </div>
    
  <% end %>
  
</div>

<h1>Listing tasks</h1>

<table border = 1>
  <tr>
    <th>Name</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th></th>
  </tr>
  
<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.created_at %></td>
    <td><%= task.updated_at %></td>
    <td><%= link_to 'Show',project_task_path(@project,task) %>
    <%= link_to 'Edit', edit_project_task_path( @project,task) %>
    <%= link_to 'Destroy', project_task_path(@project,task), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>
<p>
  <b>Project Id:</b>
  <%= @task.project_id %>
</p>
<p>
  <b>Created At:</b>
  <%= @task.created_at %>
</p>
<p>
  <b>Updated At:</b>
  <%= @task.updated_at %>
</p>

<%= link_to 'Edit', edit_project_task_path(@project,@task) %> |
<%= link_to 'Back', project_tasks_path(@project) %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>